viamrobotics/rust-utils

- src/ffi/dial_ffi.rs
- src/ffi/spatialmath/vector3.rs
- src/rpc/base_channel.rs
- src/rpc/client_channel.rs
- src/rpc/dial.rs
- src/rpc/webrtc.rs
Uses weak arc to ensure arcs are dropped appropriately, calls `close` on channels when freeing rust runtime in FFI context.
> RSDK-828 - fix file handle leak

- src/ffi/dial_ffi.rs
- src/rpc/dial.rs
Allow to optionally set an entity when doing authentication
> allow different entities when using RPCCredentials

- Cargo.toml
- src/rpc/client_channel.rs
[RSDK-2011](https://viam.atlassian.net/browse/RSDK-2011)
[`DashMap`](https://crates.io/crates/dashmap) has an almost identical API to [`CHashMap`](https://crates.io/crates/chashmap) but anecdotally has better performance under high workloads (e.g. lots of concurrent writes). Switching to `DashMap` seems to resolve hangs with async calls from the Python SDK (see RSDK-2011 and [RSDK-2070](https://viam.atlassian.net/browse/RSDK-2070)).
Note that users will still run into the issue of stream ID integer overflow in the underlying `webrtc-rs` crate until we do [RSDK-2268](https://viam.atlassian.net/browse/RSDK-2268).
[RSDK-2011]: https://viam.atlassian.net/browse/RSDK-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[RSDK-2070]: …
> RSDK-2011 Change CHashMap to DashMap for better performance

- Cargo.toml
- src/rpc/base_channel.rs
- src/rpc/client_channel.rs
- src/rpc/dial.rs
Updates us to webrtc v0.7.1, creates a blocking `close` fn for WebRTCBaseChannel to facilitate the upgrade.
> RSDK-2268 - Update webrtc version

- src/rpc/base_channel.rs
- src/rpc/client_channel.rs
- src/rpc/client_stream.rs
Major changes:
- When receiving gRPC errors, log but do not return as error (the error will still be received by users from the top level `call` function, but this avoids confusing errors that imply that any gRPC call error is a rust deserialization problem)
- Remove `close_sync` - this function was failing before because of issues creating runtimes within runtimes, which caused noisy and erroneous error messages to log when shutting down
- Add logging when dropping `WebRTCBaseChannel` to show that - despite removing the `close_sync` - we are in fact successfully dropping `WebRTCBaseChannel`s when done with them.
> RSDK-2407 - Fix gRPC error logging

- Cargo.toml
- src/rpc/dial.rs
@edaniels This includes the fix for signaling where it can come back unimplemented
> [RSDK-3103] TURN credentials are not broken

- Cargo.toml
- src/rpc/dial.rs
- src/rpc/webrtc.rs
When the webrtc crate updated to using `#[default]` instead of manually defining, a couple types had their defaults changed. One of these changes was causing stun credential failures. This updates so we no longer rely on the default.
> RSDK-3150 - fix ice server credential type

- .github/workflows/publish.yml
- .github/workflows/release.yml
- Cargo.toml
this creates the a draft release from the release action with an automated version bump. The builds are automatically populated as well
adds publish action to publish to crates
tested all the way up to actually publishing (able to run it with `--dry-run` with no issues tho)
basically follows the structure of the python workflows before we revamped it
> RSDK-3383 - Workflow updates

- src/ffi/spatialmath/orientation_vector.rs
Earlier I forgot to include a way to access the raw components of an orientation vector initialized through the FFI
> RSDK-3865 - implement get_components in spatialmath FFI

- dialdbg/src/main.rs
- dialdbg/src/parse.rs
- src/rpc/log_prefixes.rs
- When mDNS fails, add loopback support to the `dialdbg` mDNS logging query.
- When parsing logs, consider successful ICE connection to be evidence of webRTC connection to circumvent flaky log issues (to be diagnosed/solved in a subsequent ticket)
> RSDK-4035 - add loopback, webrtc connection fallback for dialdbg

- dialdbg/src/main.rs
- dialdbg/src/rtt.rs
[RSDK-3444](https://viam.atlassian.net/browse/RSDK-3444)
Adds basic RTT measuring to `dialdbg` (can be disabled with `--nortt`. When a connection is successfully established; 10 echo requests will be run using the created channel, and the average RTT will be printed as:
```
average RTT across established [type of connection] connection: 149ms
```
[RSDK-3444]: https://viam.atlassian.net/browse/RSDK-3444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RDSK-3444 Add basic RTT measuring to dialdbg

- src/dialdbg/parse.rs
- src/rpc/dial.rs
- src/rpc/log_prefixes.rs
[RSDK-4297](https://viam.atlassian.net/browse/RSDK-4297)
Include the offered local session description in dialdbg's output. It seems like issues with the created session description are common sources of difficult-to-find WebRTC bugs.
New WebRTC output from dialdbg looks like:
```
Debugging dial with WebRTC...
mDNS could not be used to connect
authentication successful in 111ms
offered local session description was
v=0
o=- 4176189070910177742 55142000 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 [redacted for security]
a=group:BUNDLE 0
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=sendrecv
a=sctp-port:5000
a=ice-ufrag:[redacted for security]
a=ice-pwd:[redacted for security]
WebRTC connection establishment successful in 3494ms
selected ICE …
```
> RSDK-4297 Include local session description in dialdbg

- .github/workflows/release.yml
Use `install_name_tool` in build action to override the github artifact install name path.
Ran the `install_name_tool` command on a dylib downloaded from github, observed corrected behavior when working with the C++ SDK.
> RSDK-1996 - use install_name_tool to fix the install path

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/rpc/dial.rs
This PR removes the interfaces crate and use local_ip_address instead. 
This is to allow the rust-utils library to be built for windows systems. 
When building for windows FFI & proxy are disable because we don't have a crate that exposes UDS sockets with AsyncRead and AsyncWrite traits defined (for example the usd-windows crate only has Read &Write traits) It should be possible to support proxying on Windows machine but it would either mean implementing AsyncWrite & AsyncRead for uds-windows or using a local UDP port.
> Remove interfaces crate

- src/ffi/dial_ffi.rs
[RSDK-4447](https://viam.atlassian.net/browse/RSDK-4447?atlOrigin=eyJpIjoiYmMxYjQwMGQ3ZTAwNGEzMDhjNjA4OTMzOTRmNzgwZjciLCJwIjoiaiJ9)
[Related changes in Python SDK](https://github.com/viamrobotics/viam-python-sdk/pull/444)
[RSDK-4447]: https://viam.atlassian.net/browse/RSDK-4447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Test procedure
- [Test with client that connects to offline robot](https://www.loom.com/share/a8a5661dd1304c55bdbd4ae4e628368c)
- [Test with robot that is online, but edited the rust-utils code to sleep at the end of the answerer code](https://www.loom.com/share/b0f459a1bc674a8b976468ac976f4781?sid=381570a9-fa45-4917-984d-ef1523073312)
> RSDK-4447: Add dial timeout

- src/dialdbg/README.md
- src/dialdbg/main.rs
- src/rpc/webrtc.rs
https://viam.atlassian.net/browse/RSDK-6043
Allow specifying `api-key` auth mechanism and `--entity`. Reports < 1ms average RTT instead of "0ms", which is misleading. Also removes an unnecessary `loop` in webRTC code.
> RSDK-6043 Support API key auth in dialdbg

- .github/workflows/release.yml
https://viam.atlassian.net/browse/RSDK-6152
Splits `aarch64` building into its own GH job with a slightly different toolchain setup. Runs the `prepare` job on a buildjet `arm64` machine instead of an `amd64` machine.
> RSDK-6152 Fix rust-utils release for aarch64

- .github/workflows/release.yml
- revert naming style of the aarch64 release artifact to the old style
- the name of this output changed between 0.1.2 and 0.1.3
- viam-cpp-sdk consumes static rust-utils from github releases [here in CMake](https://github.com/viamrobotics/viam-cpp-sdk/blob/main/CMakeLists.txt#L249)
- this causes some c++ modules to fail on arm (example CI failure [here](https://github.com/viamrobotics/module-example-cpp/actions/runs/7332307759/job/19987973787#step:7:25))
- if the new format is the superior format we can edit the URL in the cpp sdk instead
> RSDK-6194 rename arm64 release artifacts

- .github/workflows/checks.yml
- .github/workflows/license_finder.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/update_protos.yml
From Slack, we should move our workflows away from self-hosted runners to either github or buildjet hosted:
> github runners start up faster (we host the rdk-devenv image on github, so it's faster for it to pull the image) so are best for small jobs, and better than doing a 2-core runner on buildjet. Anything that really needs 4 cores or more than 4GB of ram should use buildjet probably, and scale appropriately. Typically 4 or 8 core is the right answer. I've not seen a job that can really make full use of 16 cores for a full run (though if you've got one, then it's worth considering.)
> Migrate runners

- .cargo/config.toml
- .github/workflows/release.yml
I'm not 100% on my yml syntax, but I ran the individual steps locally and it works on the `alpine` docker image.
> RSDK-4857 Add steps to build musl binaries on alpine linux

- Cargo.lock
- Cargo.toml
upstream `webrtc` crate has been updated, which picks up the fix we made a while back for `err-full` issues when too much data is coming through webrtc.
> RSDK-5784 - bump webrtc version

- examples/Cargo.lock
- examples/src/echo/main.rs
- src/rpc/client_channel.rs
- src/rpc/dial.rs
- Simplifies and corrects the "end of stream" determining logic, removes "eos" arg
- (flyby) parse `next_message_length` as a `usize` initially to reduce cases of `try_into().unwrap()`
- (flyby) remove extraneous `http` import
- (flyby) fix example code credentials template
> RSDK-7105 - Fix server streaming

- examples/Cargo.lock
- src/ffi/dial_ffi.rs
- src/rpc/dial.rs
When attempting to connect with an mDNS uri fails, we now fallthrough and attempt a standard connection.
Attempts to auth to a robot with an org level API key (or presumably any level other than the robot itself) fail when connecting with mDNS. Previously we would just fail; we've now added explicit fallback logic.
> RSDK-5993 - fallback to non-mdns uri when auth fails

- Cargo.lock
- Cargo.toml
Bumping webrtc crate version helped fix an issue with `err-full` errors when processing too much data, but unfortunately has also introduced a regression whereby connection to an esp32 now fails.
This PR reverts that webrtc version bump. The search for a more principled solution which prevents the `err-full` issues without introducing regressions is ongoing.
> RSDK-7334 - revert webrtc version bump

- .cargo/config.toml
- .github/workflows/release.yml
- Cargo.lock
To enable the Python SDK to build musl linux wheels for aarch64, armv6l, armv7, and x86 (i686), this PR adds those additional targets to the `release` workflow. I ran them on my laptop first but i have not confirmed if they'll work on the buildjet runner.
> chore: add musl build targets for arm64, v6l, v7, x86

- Cargo.lock
- Cargo.toml
We were pointing to a specific git commit for the webRTC crate to push past some buggy code that was breaking connectivity to esp32s. Now the latest webRTC crate release has that commit, so we should point to the official release rather than a github commit. Tested, confirmed that connection to an esp32 worked.
Updating `interceptor` was necessary for compatibility with the latest `webRTC` crate.
> RSDK-7422 - update webrtc crate

- .github/workflows/release.yml
Unblocking release builds until we can figure out the right parameters to support these targets: https://github.com/viamrobotics/rust-utils/actions/runs/9212826036
> chore: remove failing musl linux build targets

- src/rpc/dial.rs
Fixes an issue whereby we were improperly inferring when a connection was local by looking for `local.cloud` rather than `local.*viam*.cloud`.
This fixes grpc connection to the `local.viam.cloud` addresses, but does not yet fix connection to `localhost:8080`. Will continue to look into that in subsequent PRs but wanted to lock this in now.
> RSDK-7854 - fix remote uri inference

- src/rpc/dial.rs
[RSDK-7282](https://viam.atlassian.net/browse/RSDK-7282)
Adds info-level logs for:
- Gathering of local ICE candidates
- Reception of remote ICE candidates
- Statistics of caller updates for this connection establishment
- Number of updates
- Average duration of update
- Max duration of update
[RSDK-7282]: https://viam.atlassian.net/browse/RSDK-7282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSDK-7282 Log ICE event timings/stats

- src/rpc/dial.rs
We were generating noisy errors in `rust-utils` occasionally when trying to connect. This seemed to be the result of parallel dialing, but it happened non-deterministically. While the errors were basically harmless (one branch always succeeds and so a connection is always still formed), they were noisy and scary-looking (it could be easy to miss that a connection was in fact formed successfully and that any calls were made successfully).
Some digging revealed that the cause of this problem was a failure to receive updates from the signaling service, meaning we never set a `UUID` and so sent an empty string as our UUID. Thus, we can avoid the noisy errors by checking if the UUID is empty before sending an update request and just not sending if so. The exact cause of the problem is unknown …
> RSDK-7986 - stop logging noisy errors

- .cargo/config.toml
- .github/workflows/release.yml
Second attempt to add `musl` support for aarch64/arm build targets to support in-progress Home Assistant core integration, which requires the Python SDK to run on more platforms. See #112 for more information.
> chore(release): add ARM musl build targets

- .github/workflows/release.yml
Fixes https://github.com/viamrobotics/rust-utils/pull/122#discussion_r1672629323
> chore(release): update musl armv6l, armv7l platform name to musllinux

- Cargo.lock
- Cargo.toml
- examples/Cargo.lock
- src/rpc/dial.rs
- src/rpc/webrtc.rs
Adds support for loopback candidates in webRTC, allowing us to establish webRTC connections via mDNS in offline scenarios. Previously, offline connectivity only worked via gRPC in rust-utils.
Note that this relies on fixes to the upstream `webrtc-rs` crate which have not yet been merged. As such, we have to point to my branch of the `webrtc` crate in `Cargo.toml`. It might be good to consider whether we merge this to a separate branch than `main`, or hold off on merging until upstream fixes are merged. Either way, it seemed good to have this up at least so people can look and use as necessary.
The upstream fix, if anyone cares to see, is located at https://github.com/webrtc-rs/webrtc/pull/603
> RSDK-8469 - Fix offline dial

- .github/workflows/release.yml
All of this work was done by @njooma a couple months ago. All necessary testing to show that it could successfully build and run the upload artifacts job was done at that time. At the time the work was abandoned because there was an issue whereby we couldn't build and upload on ubuntu 18.04 while using `upload-artifacts@v4`. This was deemed unacceptable because `ubuntu 18.04` is necessary for ROS melodic, which many existing robotics companies use.
We have since determined that it's fine to deprecate support for ubuntu 18.04. Three factors influenced that choice:
1) `upload-artifacts@v3` will no longer work come end of January so we have to update it now,
2) no existing customers use ROS melodic or require ubuntu 18.04 support, and 
3) if such a customer comes along, we can make a custom …
> RSDK-9518 - update to Artifacts v4

- src/rpc/dial.rs
Fixes issue where `rust-utils` was unable to find an mDNS candidate for micro-rdk robots.
Tested locally: before change, was unable to connect to a native micro-rdk process with signaling disabled. After change, I was able to connect to the same micro-rdk process whether signaling was enabled or not. Also tested to ensure no regression in connectivity to a locally running `viam-server` process, both with wifi on and with wifi off.
cc @acmorrow
> RSDK-9300 - make mdns query more generic over local-ness of candidate

- .github/workflows/update_protos.yml
Note to reviewers: feel free to propose an alternative user icon image.
> RSDK-9904 - add job to notify slack of proto failure

- src/ffi/spatialmath/orientation_vector.rs
- src/ffi/spatialmath/quaternion.rs
- src/ffi/spatialmath/vector3.rs
fixes linter warnings that were causing tests to fail.
> make pointer refs explicit
